/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\door.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/door.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.door.geometry} material={materials.Material} />
      <mesh geometry={nodes.glass.geometry} material={nodes.glass.material} />
      <mesh geometry={nodes.rebate_edge.geometry} material={nodes.rebate_edge.material} />
      <mesh geometry={nodes.handle.geometry} material={nodes.handle.material} />
      <mesh geometry={nodes.lock_hole.geometry} material={nodes.lock_hole.material} />
      <mesh geometry={nodes.handle001.geometry} material={nodes.handle001.material} />
      <mesh geometry={nodes.lock_hole001.geometry} material={nodes.lock_hole001.material} />
    </group>
  )
}

useGLTF.preload('/door.glb')
