/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:/Users/USER/Desktop/Coding Projects/3d_configurator/public/models/door.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DoorModelJSX(props) {
  const { nodes, materials } = useGLTF("/models/door.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.door.geometry}
        material={materials.Material}
        position={[1.2, 2.1, -0.971]}
      />
      <mesh
        geometry={nodes.glass.geometry}
        material={nodes.glass.material}
        position={[0.883, 3.492, -0.004]}
      />
      <mesh
        geometry={nodes.handle.geometry}
        material={nodes.handle.material}
        position={[0.361, 2.791, -1.013]}
        rotation={[-Math.PI, 0, 0]}
        scale={2.692}
      />
      <mesh
        geometry={nodes.lock_hole.geometry}
        material={nodes.lock_hole.material}
        position={[0.358, 2.354, -1.011]}
        rotation={[-Math.PI, 0, 0]}
        scale={2.692}
      />
      <mesh
        geometry={nodes.handle001.geometry}
        material={nodes.handle001.material}
        position={[0.362, 2.14, -0.925]}
        scale={2.692}
      />
      <mesh
        geometry={nodes.lock_hole001.geometry}
        material={nodes.lock_hole001.material}
        position={[0.359, 2.219, -0.927]}
        scale={2.692}
      />
    </group>
  );
}

useGLTF.preload("/models/door.glb");
